tremorzilla-no-yeet = false
lux-no-damage-modifier = false
lux-no-jump = false
flying-hullbreaker = false
crossbow-shoot-nuke = false
larger_meteor = false
enable-magnetic-orbs = false
magnetic-orbs-no-break = false

