
#Animals
[animals]
	#How much longer should it take for a baby animal to age?
	#Range: 0.0 ~ 1.0
	breeding_mulitplier = 1
	#How much longer should it take for an animal to be able to breed again?
	#Range: 1.0 ~ 1.7976931348623157E308
	age_multiplier = 8
	#Nutrition of wild animals.
	#Range: 0.0 ~ 1.0
	nutrition_multiplier = 0.3

#Mobs
[mobs]
	#Chance that an undead mob will spawn with an animal hood.
	#Range: 0.0 ~ 1.0
	hoodChanceMultiplier = 0.01
	#Chance that a carcass applies its bloody effects per inventory tick. (Default 1/1000) Raising this can decrease server lag.
	#Range: > 1
	armyHoodChanceMultiplier = 1000

