
#Make sure config changes are duplicated on both Clients and the Server when running a dedicated Server,
# as the config isnt synced between Clients and Server.
#General Settings
[general]
	#Forge Energy conversion rate (in FE/t at 256 RPM, value is the FE/t generated and consumed is at 256rpm).
	#Range: > 0
	fe_at_max_rpm = 5000
	#Max stress for the Alternator and Electric Motor (in SU at 256 RPM).
	#Range: > 0
	max_stress = 16384
	#If audio should be enabled or not.
	audio_enabled = true

#Electric Motor
[electric_motor]
	#Electric Motor min/max RPM.
	#Range: > 1
	motor_rpm_range = 256
	#Electric Motor minimum required energy consumption in FE/t.
	#Range: > 0
	motor_min_consumption = 8
	#Electric Motor max input in FE (Energy transfer not consumption).
	#Range: > 0
	motor_max_input = 50000
	#Electric Motor internal capacity in FE.
	#Range: > 0
	motor_capacity = 50000

#Alternator
[alternator]
	#Alternator max input in FE (Energy transfer, not generation).
	#Range: > 0
	generator_max_output = 50000
	#Alternator internal capacity in FE.
	#Range: > 0
	generator_capacity = 50000
	#Alternator efficiency relative to base conversion rate.
	#Range: 0.01 ~ 1.0
	generator_efficiency = 1

#Rolling Mill
[rolling_mill]
	#Rolling Mill duration in ticks.
	#Range: > 0
	rolling_mill_processing_duration = 100
	#Rolling Mill base stress impact.
	#Range: 0 ~ 1024
	rolling_mill_stress = 16

#Wires
[wires]
	#Small Connector max input in FE/t (Energy transfer).
	#Range: > 0
	small_connector_max_input = 10000
	#Small Connector max output in FE/t (Energy transfer).
	#Range: > 0
	small_connector_max_output = 10000
	#Small Connector max wire length in blocks.
	#Range: 0 ~ 256
	small_connector_wire_length = 32
	#Small Connector With Light energy consumption in FE/t.
	#Range: > 0
	small_light_connector_consumption = 100
	#Large Connector max input in FE/t (Energy transfer).
	#Range: > 0
	large_connector_max_input = 100000
	#Large Connector max output in FE/t (Energy transfer).
	#Range: > 0
	large_connector_max_output = 100000
	#Large Connector max wire length in blocks.
	#Range: 0 ~ 256
	large_connector_wire_length = 64
	#Ignore checking if block face can support connector.
	connector_ignore_face_check = false
	#Allows blocks attached to a connector to freely pass energy to and from the connector network.
	connector_allow_passive_io = true

#Accumulator
[accumulator]
	#Accumulator max input in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_input = 500000
	#Accumulator max output in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_output = 500000
	#Accumulator internal capacity per block in FE.
	#Range: > 0
	accumulator_capacity = 10000000
	#Accumulator max multiblock height.
	#Range: 1 ~ 8
	accumulator_max_height = 8
	#Accumulator max multiblock width.
	#Range: 1 ~ 8
	accumulator_max_width = 5

#Portable Energy Interface
[portable_energy_interface]
	#PEI max input in FE/t (Energy transfer).
	#Range: > 0
	pei_max_input = 500000
	#PEI max output in FE/t (Energy transfer).
	#Range: > 0
	pei_max_output = 500000

#Tesla Coil
[tesla_coil]
	#Tesla Coil max input in FE/t (Energy transfer).
	#Range: > 0
	tesla_coil_max_input = 100000
	#Tesla Coil charge rate in FE/t.
	#Range: > 0
	tesla_coil_charge_rate = 50000
	#Tesla Coil charge rate in FE/t for recipes.
	#Range: > 0
	tesla_coil_recipe_charge_rate = 20000
	#Tesla Coil internal capacity in FE.
	#Range: > 0
	tesla_coil_capacity = 400000
	#Energy consumed when Tesla Coil is fired (in FE).
	#Range: > 0
	tesla_coil_hurt_energy_required = 5000
	#Hurt range (in blocks/meters).
	#Range: > 0
	tesla_coil_hurt_range = 4
	#Damaged dealt to mobs when Tesla Coil is fired (in half hearts).
	#Range: > 0
	tesla_coil_hurt_mob = 4
	#The duration of the Shocked effect for mobs (in ticks).
	#Range: > 0
	tesla_coil_effect_time_mob = 20
	#Damaged dealt to players when Tesla Coil is fired (in half hearts).
	#Range: > 0
	tesla_coil_hurt_player = 2
	#The duration of the Shocked effect for players (in ticks).
	#Range: > 0
	tesla_coil_effect_time_player = 20
	#Tesla Coil fire interval (in ticks).
	#Range: > 0
	tesla_coil_fire_cooldown = 20

#Misc
[misc]
	#Diamond Grit Sandpaper durability (number of uses).
	#Range: > 3
	diamond_grit_sandpaper_uses = 1024
	#Barbed Wire Damage.
	#Range: 0.0 ~ 3.4028234663852886E38
	barbed_wire_damage = 5

