
["Client Configs"]
	#Fuel type tooltip on Buckets
	"Fuel tooltips" = false
	#Whenever Diesel Engines display in JEI
	"Diesel Engine JEI Config" = true
	#Diesel Engines emit sounds on trains
	"Diesel Engines emit sounds on trains" = true

