
["Render Radius"]
	#displayFeedbackButtonOnPauseScreen
	displayFeedbackButtonOnPauseScreen = true
	#displayFeedbackButtonOnInventoryScreen
	displayFeedbackButtonOnInventoryScreen = false
	#displayFeedbackButtonOnDeathScreen
	displayFeedbackButtonOnDeathScreen = false

