name: å‘å¸ƒæœåŠ¡ç«¯åŒ…
run-name: ${{ github.actor }} æ­£åœ¨å‘å¸ƒæœåŠ¡ç«¯æ–°ç‰ˆæœ¬ğŸš€
on:
  push:
    branches:
      - test-release
      - release

jobs:
  Release:
    runs-on: ubuntu-latest
    name: å‘å¸ƒğŸš€
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: main
      - name: è¯»å–æ•´åˆåŒ…å
        uses: SebRollen/toml-action@v1.2.0
        id: read-modpackname
        with:
          file: ${{ github.workspace }}/main/pack.toml
          field: 'name'
      - name: è¯»å–æ•´åˆåŒ…ç‰ˆæœ¬å·
        uses: SebRollen/toml-action@v1.2.0
        id: read-version
        with:
          file: ${{ github.workspace }}/main/pack.toml
          field: 'version'
      - name: ç”Ÿæˆæ•´åˆåŒ…nightlyæ„å»ºåç¼€
        run: |
          echo ${{ steps.read-modpackname.outputs.value }}
          echo ${{ steps.read-version.outputs.value }}
          if [[ $GITHUB_REF == refs/heads/test-release ]]; then
            VERSION_SUFFIX=$(date +%m%d%H%M)
            echo "VERSION_SUFFIX=-$VERSION_SUFFIX" >> $GITHUB_OUTPUT
            echo "Nightly!"
          else
            echo "VERSION_SUFFIX=" >> $GITHUB_OUTPUT
          fi
          echo ${{ steps.set_version.outputs.VERSION_SUFFIX }}
      # - name: è¯»å–mcç‰ˆæœ¬å·
      #   uses: SebRollen/toml-action@v1.2.0
      #   id: read-minecraft
      #   with:
      #     file: ${{ github.workspace }}/main/pack.toml
      #     field: 'versions.minecraft'
      # - name: è¯»å–forgeç‰ˆæœ¬å·
      #   uses: SebRollen/toml-action@v1.2.0
      #   id: read-forge
      #   with:
      #     file: ${{ github.workspace }}/main/pack.toml
      #     field: 'versions.forge'
      # - name: è¾“å‡ºç‰ˆæœ¬å·å’ŒåŒ…å
      #   run: |
      #     echo ${{ steps.read-modpackname.outputs.value }}
      #     echo ${{ steps.read-version.outputs.value }}
      #     echo ${{ steps.read-forge.outputs.value }}
      #     echo ${{ steps.read-minecraft.outputs.value }}
      # - name: ä¸‹è½½forge
      #   env:
      #     MINECRAFT: ${{ steps.read-minecraft.outputs.value }}
      #     FORGE: ${{ steps.read-forge.outputs.value }}
      #   run: |
      #     URL="https://maven.minecraftforge.net/net/minecraftforge/forge/$MINECRAFT-$FORGE/forge-$MINECRAFT-$FORGE-installer.jar"
      #     echo "$URL"
      #     curl -L -o ${{ github.workspace }}/main/forge-installer.jar "$URL"
      # - name: å®‰è£…forge
      #   run: |
      #     cd ${{ github.workspace }}/main && java -jar forge-installer.jar nogui --installServer
      # - name: list file
      #   run: |
      #     ls ${{ github.workspace }}/main
      - name: Read and delete packwiz ignore files
        run: |
            mapfile -t prefixes < ${{ github.workspace }}/main/.packwizignore
            for prefix in "${prefixes[@]}"; do
              echo "Deleting files with prefix: $prefix"
              find ${{ github.workspace }}/main -name "${prefix}*" -exec rm {} +
            done
      - name: Read and delete mods
        run: |
            mapfile -t prefixes < ${{ github.workspace }}/main/.clientonlymodlist
            for prefix in "${prefixes[@]}"; do
              echo "Deleting files with prefix: $prefix"
              find ${{ github.workspace }}/main/mods -name "${prefix}*" -exec rm {} +
            done
      - name: list remained files & mods
        run: |
          ls ${{ github.workspace }}/main
          ls ${{ github.workspace }}/main/mods
      - name: ä¸Šä¼ å¸¦modåŒ…
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.read-modpackname.outputs.value }}-${{ steps.read-version.outputs.value }}${{ steps.set_version.outputs.VERSION_SUFFIX }}-server
          path: ${{ github.workspace }}/main
      - run: echo "ğŸ This job's status is ${{ job.status }}."
