name: å‘å¸ƒæœåŠ¡ç«¯åŒ…
run-name: ${{ github.actor }} æ­£åœ¨å‘å¸ƒæœåŠ¡ç«¯æ–°ç‰ˆæœ¬ğŸš€ - TESTING
on:
  push:
    branches:
      - release-server-*

jobs:
  Release:
    runs-on: ubuntu-latest
    name: å‘å¸ƒğŸš€
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: main
      - name: è¯»å–åŒ…å
        uses: SebRollen/toml-action@v1.2.0
        id: read-modpackname
        with:
          file: ${{ github.workspace }}/main/pack.toml
          field: 'name'
      - name: è¯»å–ç‰ˆæœ¬å·
        uses: SebRollen/toml-action@v1.2.0
        id: read-version
        with:
          file: ${{ github.workspace }}/main/pack.toml
          field: 'version'
      - name: è¾“å‡ºç‰ˆæœ¬å·å’ŒåŒ…å
        run: |
          echo ${{ steps.read-modpackname.outputs.value }}
          echo ${{ steps.read-version.outputs.value }}
      - name: ç§»é™¤.hmclversion.cfg
        run: |
          rm ${{ github.workspace }}/main/.hmclversion.cfg
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'Griefed/ServerPackCreator'
          file: "ServerPackCreator-7_1_8-Installer-Linux-amd64.sh"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read and delete files
        run: |
            mapfile -t prefixes < ${{ github.workspace }}/main/.clientonlymodlist
            for prefix in "${prefixes[@]}"; do
              echo "Deleting files with prefix: $prefix"
              find ${{ github.workspace }}/main/mods -name "${prefix}*" -exec rm {} +
            done
      - name: list remained mod
        run: |
          ls ${{ github.workspace }}/main/mods
      - name: ä¸Šä¼ å¸¦modåŒ…
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.read-modpackname.outputs.value }}-${{ steps.read-version.outputs.value }}-server
          path: ${{ github.workspace }}/main
      - run: echo "ğŸ This job's status is ${{ job.status }}."
